In [33]:
import numpy as np
import pandas as pd
from pathlib import Path

In [34]:
cwd=Path.cwd()
parrent_dir=cwd.parent
print(parrent_dir)
# Read the csv file
df = pd.read_csv(parrent_dir/'data-scraped'/'appartment_cleaned_interim.csv')
df.head(10)

d:\bits\Sem3\mloops Projects\ml-project-banglore-flats

,apartment_name,appartment_loc,zone,bhk_type,construction_status,carpet_area,bulit_area,super_bulit_area,price_value,nearbylocation,facility,luxury_facility_scores,luxury_category
0,nambiar millennia,Sarjapur Road,east,1,Under Construction,NaN,668.0,NaN,0.53,"[('mahatma vidhyalaya', '400 m'), ('eterssrt m...","['Yoga/Meditation Area', ""Children's Play Area...",69.0,medium
1,provident capella,Samethanahalli,east,1,New Property,NaN,431.0,480.0,0.55,"[('soukya road', '1.4 km'), ('mvj college of e...","[""Children's Play Area"", 'Creche/Day Care', 'J...",70.0,medium
2,brigade citre budigere cross,Byrathi,east,1,New Property,NaN,619.0,689.0,0.69,"[('one world international school', '3.2kms'),...","['Pet Park', ""Children's Play Area"", 'Landscap...",50.0,medium
3,sattva east crest bandapura,Budigere Cross,east,1,New Property,NaN,537.0,598.0,0.70,"[('prerana international school', '700 m'), ('...","['Banquet Hall', 'Creche/Day Care', ""Children'...",74.0,medium
4,sowparnika columns,Soukya Road,east,1,New Property,486.0,619.0,736.0,0.52,"['Whitefield Kadugodi Metro Station', 'Nexus S...","['Lift(s)', 'Swimming Pool', 'Park', 'Fitness ...",44.0,low
5,sattva east crest,Bandapura,east,1,Relatively New,384.0,497.0,598.0,0.65,"['Orion Uptown Mall', 'Raghuvanahalli - Hosako...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...",123.0,medium
6,godrej splendour,Whitefield,east,1,New Property,NaN,544.0,605.0,0.69,"['Whitefield (Kadugodi) Metro Station', 'Ascen...","['Intercom Facility', 'Lift(s)', 'Separate ent...",107.0,medium
7,artha neo midas,Hoskote,east,1,Moderatly Old,NaN,484.0,539.0,0.23,"['Dhruva Nursing Home And Diagnostic Centre', ...","['Lift(s)', 'Park', 'Fitness Centre / GYM', 'C...",30.0,low
8,sowparnika ashiyana,Whitefield,east,1,New Property,NaN,413.0,460.0,0.50,"['Kadugodi Metro Station', 'Nexus Shantiniketa...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",116.0,medium
9,sankaalp residency,Coconut Grove Layout,east,1,Old,750.0,800.0,NaN,0.22,"['Temple', 'Shiva', 'Hanuman', 'Hanuman Temple...","['Feng Shui / Vaastu Compliant', 'Security / F...",22.0,low

In [35]:
df.isnull().sum()

apartment_name               0
appartment_loc               0
zone                         0
bhk_type                     0
construction_status          0
carpet_area               2646
bulit_area                   0
super_bulit_area          2406
price_value                  0
nearbylocation             281
facility                   501
luxury_facility_scores      68
luxury_category              0
dtype: int64

In [36]:
df.dropna(subset=['nearbylocation','facility'], inplace=True)

In [37]:
df.isnull().sum()

apartment_name               0
appartment_loc               0
zone                         0
bhk_type                     0
construction_status          0
carpet_area               2197
bulit_area                   0
super_bulit_area          1930
price_value                  0
nearbylocation               0
facility                     0
luxury_facility_scores      65
luxury_category              0
dtype: int64

In [38]:
df.shape

(5355, 13)

#carpet to built up ratio:  0.8416612442582418
#super to built up ratio:  1.1127433971009146

In [39]:
# both super is null and built up present built up null

sc_df = df[df['super_bulit_area'].isnull()]

In [40]:
sc_df.loc[:,'super_bulit_area'] = round(sc_df['bulit_area'] * 1.127,2)

In [41]:
df.update(sc_df)

In [42]:
df.isnull().sum()

apartment_name               0
appartment_loc               0
zone                         0
bhk_type                     0
construction_status          0
carpet_area               2197
bulit_area                   0
super_bulit_area             0
price_value                  0
nearbylocation               0
facility                     0
luxury_facility_scores      65
luxury_category              0
dtype: int64

In [43]:
loc_df = pd.read_csv('loc_find.csv')

In [44]:
loc_df.columns

Index(['apartment_name', 'appartment_loc', 'Latitude', 'Longitude',
       'corrected_apartment_name', 'corrected_appartment_loc'],
      dtype='object')

In [45]:
merged_df = pd.merge(
    df,
    loc_df,
    on=['apartment_name', 'appartment_loc'],  # Columns to join on
    how='inner'  # Inner join
)

In [46]:
merged_df.head()

,apartment_name,appartment_loc,zone,bhk_type,construction_status,carpet_area,bulit_area,super_bulit_area,price_value,nearbylocation,facility,luxury_facility_scores,luxury_category,Latitude,Longitude,corrected_apartment_name,corrected_appartment_loc
0,nambiar millennia,Sarjapur Road,east,1,Under Construction,NaN,668.0,752.84,0.53,"[('mahatma vidhyalaya', '400 m'), ('eterssrt m...","['Yoga/Meditation Area', ""Children's Play Area...",69.0,medium,12.8925,77.7795,Nambiar Millennia,Sarjapur Road
1,provident capella,Samethanahalli,east,1,New Property,NaN,431.0,480.00,0.55,"[('soukya road', '1.4 km'), ('mvj college of e...","[""Children's Play Area"", 'Creche/Day Care', 'J...",70.0,medium,12.9955,77.7655,Provident Capella,Samethanahalli
2,brigade citre budigere cross,Byrathi,east,1,New Property,NaN,619.0,689.00,0.69,"[('one world international school', '3.2kms'),...","['Pet Park', ""Children's Play Area"", 'Landscap...",50.0,medium,13.0155,77.7255,Brigade Citrine Budigere Cross,Byrathi
3,sattva east crest bandapura,Budigere Cross,east,1,New Property,NaN,537.0,598.00,0.70,"[('prerana international school', '700 m'), ('...","['Banquet Hall', 'Creche/Day Care', ""Children'...",74.0,medium,13.0468,77.7473,Sattva East Crest Bandapura,Budigere Cross
4,sowparnika columns,Soukya Road,east,1,New Property,486.0,619.0,736.00,0.52,"['Whitefield Kadugodi Metro Station', 'Nexus S...","['Lift(s)', 'Swimming Pool', 'Park', 'Fitness ...",44.0,low,12.9955,77.7655,Sowparnika Columns,Soukya Road

In [47]:
merged_df.shape

(5345, 17)

In [48]:
merged_df.drop(columns=['apartment_name', 'appartment_loc'], inplace=True)

In [49]:
merged_df.rename(columns={
    'corrected_appartment_loc': 'apartment_loc',
    'corrected_apartment_name': 'apartment_name',
}, inplace=True)

In [50]:
merged_df.isnull().sum()

zone                         0
bhk_type                     0
construction_status          0
carpet_area               2204
bulit_area                   0
super_bulit_area             0
price_value                  0
nearbylocation               0
facility                     0
luxury_facility_scores      64
luxury_category              0
Latitude                     0
Longitude                    0
apartment_name               0
apartment_loc                0
dtype: int64

In [73]:
merged_df

,zone,bhk_type,construction_status,carpet_area,bulit_area,super_bulit_area,price_value,nearbylocation,facility,luxury_facility_scores,luxury_category,Latitude,Longitude,apartment_name,apartment_loc
0,east,1,Under Construction,NaN,668.0,752.84,0.53,"[('mahatma vidhyalaya', '400 m'), ('eterssrt m...","['Yoga/Meditation Area', ""Children's Play Area...",69.0,medium,12.8925,77.7795,Nambiar Millennia,Sarjapur Road
1,east,1,New Property,NaN,431.0,480.00,0.55,"[('soukya road', '1.4 km'), ('mvj college of e...","[""Children's Play Area"", 'Creche/Day Care', 'J...",70.0,medium,12.9955,77.7655,Provident Capella,Samethanahalli
2,east,1,New Property,NaN,619.0,689.00,0.69,"[('one world international school', '3.2kms'),...","['Pet Park', ""Children's Play Area"", 'Landscap...",50.0,medium,13.0155,77.7255,Brigade Citrine Budigere Cross,Byrathi
3,east,1,New Property,NaN,537.0,598.00,0.70,"[('prerana international school', '700 m'), ('...","['Banquet Hall', 'Creche/Day Care', ""Children'...",74.0,medium,13.0468,77.7473,Sattva East Crest Bandapura,Budigere Cross
4,east,1,New Property,486.0,619.0,736.00,0.52,"['Whitefield Kadugodi Metro Station', 'Nexus S...","['Lift(s)', 'Swimming Pool', 'Park', 'Fitness ...",44.0,low,12.9955,77.7655,Sowparnika Columns,Soukya Road
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5340,west,4,Moderatly Old,1800.0,2000.0,2170.00,4.00,"['Mahakavi Kuvempu', 'Orion Mall', 'Christ The...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN,high,12.9985,77.5545,Brigade Gateway,Rajajinagar
5341,west,4,Relatively New,1520.0,1878.0,2171.00,2.50,"['Nagasandra', 'BIEC', 'AH 47', 'Soundarya Art...","['Security / Fire Alarm', 'Power Back-up', 'Fe...",NaN,high,13.0685,77.5925,Prestige Jindal City,Tumkur Road
5342,west,4,Relatively New,2000.0,2200.0,2500.00,3.85,"['Krantiveera Sangolli Rayanna Metro', 'Lulu M...","['Centrally Air Conditioned', 'Water purifier'...",NaN,high,12.9755,77.5555,Prestige West Woods,Okalipuram
5343,west,4,New Property,1429.0,1824.0,2171.00,5.00,"['KSR Metro Station', 'Lulu Mall Bengaluru', '...","['Intercom Facility', 'Lift(s)', 'Separate ent...",NaN,high,12.9985,77.5545,Sobha Rajvilas,Rajajinagar
5344,west,4,Relatively New,2077.0,3037.0,3422.70,2.75,"['Kengeri, Station', 'Gopalan Arcade Mall', 'N...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...",NaN,high,12.9055,77.5355,Lea Sunflower,Kengeri

In [75]:
merged_df['price_per_sqft'] = (merged_df['price_value'] * 1e7) / merged_df['super_bulit_area']

In [76]:
# Select only numeric columns for aggregation
numeric_columns = ['price_per_sqft', 'bulit_area', 'Latitude', 'Longitude']
grouped_df = merged_df.groupby('apartment_loc')[numeric_columns].mean()
grouped_df.head()

                            price_per_sqft  bulit_area  Latitude  Longitude
apartment_loc
100 Feet Road Indira Nagar    13384.353550      3149.0   12.9755    77.6355
1st Block BEL Layout           7259.820924      1650.0   13.0179    77.5268
1st Block HBR Layout           9589.819550      2228.5   13.0040    77.6385
1st Block Rajajinagar         12927.346939      2192.0   12.9985    77.5545
1st N Block Rajajinagar       26153.846154      1682.0   12.9755    77.5555

In [77]:
import plotly.express as px

In [141]:
df = grouped_df.reset_index()
fig = px.scatter_map(df, lat="Latitude", lon="Longitude",     color="price_per_sqft", size="bulit_area",hover_name="apartment_loc",
                  color_continuous_scale=px.colors.cyclical.IceFire, size_max=15, zoom=10)
fig.show()

In [131]:
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
# Start with a base Plotly figure with a mapbox
fig = go.Figure()
# Add the scatter points from your dataframe
fig.add_trace(go.Scattermapbox(
    lat=df['Latitude'],
    lon=df['Longitude'],
    mode='markers',
    marker=dict(
        size=df['bulit_area']/100,  # Adjust divisor as needed based on your data
        sizemode='area',
        sizeref=0.1,  # Controls the scaling of the markers
        color=df['price_per_sqft'],
        colorscale='IceFire',
        showscale=True,
        colorbar=dict(title="Price per sqft")
    ),
    text=df['apartment_loc'],
    hoverinfo='text',
    name='Properties'
))

# Define the North Bangalore coordinates
north_bangalore_coords = [
    [77.56, 13.14],  # Northeast
    [77.66, 13.03],  # Southeast  
    [77.58, 12.97],  # Southwest
    [77.50, 13.17],  # Northwest
    [77.56, 13.14]   # Close the polygon by returning to first point
]
# Extract the longitude and latitude lists
lons = [coord[0] for coord in north_bangalore_coords]
lats = [coord[1] for coord in north_bangalore_coords]
# Add a polygon shape to represent North Bangalore
fig.add_trace(go.Scattermapbox(
    lat=lats,
    lon=lons,
    mode='lines',
    fill='toself',
    fillcolor='rgba(0, 100, 80, 0.2)',  # Semi-transparent teal color
    line=dict(color='rgba(0, 100, 80, 0.8)', width=2),
    name='North Bangalore'
))
# Add a text label for the region
fig.add_trace(go.Scattermapbox(
    lat=[13.05],  # Center point latitude of the region (approximate)
    lon=[77.58],  # Center point longitude of the region (approximate)
    mode='text',
    text=['North Bangalore'],
    textfont=dict(size=14, color='black'),
    name='Region Label',
    showlegend=False
))

# Define South Bangalore coordinates
south_bangalore_coords = [
    [77.62, 12.93],  # Southwest (Jayanagar, BTM Layout)
    [77.67, 12.88],  # Southeast (Bannerghatta Road, Kanakapura Road)
    [77.55, 12.99],  # Northwest (Rajarajeshwari Nagar, Yelahanka)
    [77.65, 13.03],  # Northeast (Uttarahalli, Whitefield)
    [77.62, 12.93]   # Close the polygon
]
# Add South Bangalore region
south_lons = [coord[0] for coord in south_bangalore_coords]
south_lats = [coord[1] for coord in south_bangalore_coords]
fig.add_trace(go.Scattermapbox(
    lat=south_lats,
    lon=south_lons,
    mode='lines',
    fill='toself',
    fillcolor='rgba(255, 165, 0, 0.2)',  # Semi-transparent orange
    line=dict(color='rgba(255, 165, 0, 0.8)', width=2),
    name='South Bangalore'
))
# Add South Bangalore label
fig.add_trace(go.Scattermapbox(
    lat=[12.93],
    lon=[77.60],
    mode='text',
    text=['South Bangalore'],
    textfont=dict(size=14, color='black'),
    showlegend=False
))

# Define East Bangalore coordinates
# Converting DMS to decimal degrees
east_bangalore_coords = [
    [77.59, 12.9768],  # Northwest (12°58′36.46″N, 77°35′24.30″E)
    [77.661, 13.0283],  # Northeast (13°01′42.00″N, 77°39′24.00″E)
    [77.5945, 12.9716],  # Southeast (12°58′17.7564″N, 77°35′40.4376″E)
    [77.54, 12.9233],  # Southwest (12°55′24.00″N, 77°32′24.00″E)
    [77.59, 12.9768]   # Close the polygon
]
# Add East Bangalore region
east_lons = [coord[0] for coord in east_bangalore_coords]
east_lats = [coord[1] for coord in east_bangalore_coords]
fig.add_trace(go.Scattermapbox(
    lat=east_lats,
    lon=east_lons,
    mode='lines',
    fill='toself',
    fillcolor='rgba(138, 43, 226, 0.2)',  # Semi-transparent purple
    line=dict(color='rgba(138, 43, 226, 0.8)', width=2),
    name='East Bangalore'
))
# Add East Bangalore label
fig.add_trace(go.Scattermapbox(
    lat=[12.95],
    lon=[77.62],
    mode='text',
    text=['East Bangalore'],
    textfont=dict(size=14, color='black'),
    showlegend=False
))

# Define West Bangalore coordinates
west_bangalore_coords = [
    [77.51, 12.99],  # North-West
    [77.61, 12.99],  # North-East
    [77.61, 12.91],  # South-East
    [77.51, 12.91],  # South-West
    [77.51, 12.99]   # Close the polygon
]
# Add West Bangalore region
west_lons = [coord[0] for coord in west_bangalore_coords]
west_lats = [coord[1] for coord in west_bangalore_coords]
fig.add_trace(go.Scattermapbox(
    lat=west_lats,
    lon=west_lons,
    mode='lines',
    fill='toself',
    fillcolor='rgba(65, 105, 225, 0.2)',  # Semi-transparent royal blue
    line=dict(color='rgba(65, 105, 225, 0.8)', width=2),
    name='West Bangalore'
))
# Add West Bangalore label
fig.add_trace(go.Scattermapbox(
    lat=[12.95],
    lon=[77.56],
    mode='text',
    text=['West Bangalore'],
    textfont=dict(size=14, color='black'),
    showlegend=False
))

# Update the layout to ensure proper rendering and interactivity
fig.update_layout(
    mapbox=dict(
        style="open-street-map",
        center=dict(lat=13.05, lon=77.58),  # Center of North Bangalore
        zoom=5,
    ),
    height=700,  # Increase height for better visibility
    width=1400,   # Adjust width as needed
    legend=dict(
        yanchor="top",
        y=0.99,
        xanchor="left",
        x=0.01
    ),
    # Add explicit mapbox configuration with zoom controls
    mapbox_zoom=10.5,
    updatemenus=[
        dict(
            type="buttons",
            direction="left",
            buttons=[
                dict(
                    args=[{"mapbox.zoom": 10.5}],
                    label="Zoom Out",
                    method="relayout"
                ),
                dict(
                    args=[{"mapbox.zoom": 13.2}],
                    label="Zoom In",
                    method="relayout"
                )
            ],
            pad={"r": 10, "t": 10},
            showactive=False,
            x=0.11,
            xanchor="left",
            y=1.1,
            yanchor="top"
        )
    ]
)
fig.show()

In [138]:
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
# Start with a base Plotly figure with a mapbox
fig = go.Figure()
# Add the scatter points from your dataframe
fig.add_trace(go.Scattermapbox(
    lat=df['Latitude'],
    lon=df['Longitude'],
    mode='markers',
    marker=dict(
        size=df['bulit_area']/100,  # Adjust divisor as needed based on your data
        sizemode='area',
        sizeref=0.1,  # Controls the scaling of the markers
        color=df['price_per_sqft'],
        colorscale='IceFire',
        showscale=True,
        colorbar=dict(title="Price per sqft")
    ),
    text=df['apartment_loc'],
    hoverinfo='text',
    name='Properties'
))

# Define the North Bangalore coordinates
north_bangalore_coords = [
    [77.50, 13.17],
    [77.66, 13.14],
    [77.66, 13.03],
    [77.50, 13.03],
    [77.50, 13.17]
]
# Extract the longitude and latitude lists
lons = [coord[0] for coord in north_bangalore_coords]
lats = [coord[1] for coord in north_bangalore_coords]
# Add a polygon shape to represent North Bangalore
fig.add_trace(go.Scattermapbox(
    lat=lats,
    lon=lons,
    mode='lines',
    fill='toself',
    fillcolor='rgba(0, 100, 80, 0.2)',  # Semi-transparent teal color
    line=dict(color='rgba(0, 100, 80, 0.8)', width=2),
    name='North Bangalore'
))
# Add a text label for the region
fig.add_trace(go.Scattermapbox(
    lat=[13.10],  # Center point latitude of the region (approximate)
    lon=[77.58],  # Center point longitude of the region (approximate)
    mode='text',
    text=['North Bangalore'],
    textfont=dict(size=14, color='black'),
    name='Region Label',
    showlegend=False
))

# Define South Bangalore coordinates
south_bangalore_coords = [
    [77.52, 12.93],
    [77.68, 12.93],
    [77.68, 12.87],
    [77.52, 12.87],
    [77.52, 12.93]
]
# Add South Bangalore region
south_lons = [coord[0] for coord in south_bangalore_coords]
south_lats = [coord[1] for coord in south_bangalore_coords]
fig.add_trace(go.Scattermapbox(
    lat=south_lats,
    lon=south_lons,
    mode='lines',
    fill='toself',
    fillcolor='rgba(255, 165, 0, 0.2)',  # Semi-transparent orange
    line=dict(color='rgba(255, 165, 0, 0.8)', width=2),
    name='South Bangalore'
))
# Add South Bangalore label
fig.add_trace(go.Scattermapbox(
    lat=[12.90],
    lon=[77.60],
    mode='text',
    text=['South Bangalore'],
    textfont=dict(size=14, color='black'),
    showlegend=False
))

# Define East Bangalore coordinates
east_bangalore_coords = [
    [77.60, 13.02],
    [77.75, 13.02],
    [77.75, 12.92],
    [77.60, 12.92],
    [77.60, 13.02]
]
# Add East Bangalore region
east_lons = [coord[0] for coord in east_bangalore_coords]
east_lats = [coord[1] for coord in east_bangalore_coords]
fig.add_trace(go.Scattermapbox(
    lat=east_lats,
    lon=east_lons,
    mode='lines',
    fill='toself',
    fillcolor='rgba(138, 43, 226, 0.2)',  # Semi-transparent purple
    line=dict(color='rgba(138, 43, 226, 0.8)', width=2),
    name='East Bangalore'
))
# Add East Bangalore label
fig.add_trace(go.Scattermapbox(
    lat=[12.97],
    lon=[77.67],
    mode='text',
    text=['East Bangalore'],
    textfont=dict(size=14, color='black'),
    showlegend=False
))

# Define West Bangalore coordinates
west_bangalore_coords = [
    [77.45, 13.02],
    [77.60, 13.02],
    [77.60, 12.92],
    [77.45, 12.92],
    [77.45, 13.02]
]
# Add West Bangalore region
west_lons = [coord[0] for coord in west_bangalore_coords]
west_lats = [coord[1] for coord in west_bangalore_coords]
fig.add_trace(go.Scattermapbox(
    lat=west_lats,
    lon=west_lons,
    mode='lines',
    fill='toself',
    fillcolor='rgba(65, 105, 225, 0.2)',  # Semi-transparent royal blue
    line=dict(color='rgba(65, 105, 225, 0.8)', width=2),
    name='West Bangalore'
))
# Add West Bangalore label
fig.add_trace(go.Scattermapbox(
    lat=[12.95],
    lon=[77.56],
    mode='text',
    text=['West Bangalore'],
    textfont=dict(size=14, color='black'),
    showlegend=False
))

# Update the layout to ensure proper rendering and interactivity
fig.update_layout(
    mapbox=dict(
        style="open-street-map",
        center=dict(lat=13.05, lon=77.58),  # Center of North Bangalore
        zoom=5,
    ),
    height=700,  # Increase height for better visibility
    width=1400,   # Adjust width as needed
    legend=dict(
        yanchor="top",
        y=0.99,
        xanchor="left",
        x=0.01
    ),
    # Add explicit mapbox configuration with zoom controls
    mapbox_zoom=11
    # updatemenus=[
    #     dict(
    #         type="buttons",
    #         direction="left",
    #         buttons=[
    #             dict(
    #                 args=[{"mapbox.zoom": 10.5}],
    #                 label="Zoom Out",
    #                 method="relayout"
    #             ),
    #             dict(
    #                 args=[{"mapbox.zoom": 12}],
    #                 label="Zoom In",
    #                 method="relayout"
    #             )
    #         ],
    #         pad={"r": 10, "t": 10},
    #         showactive=False,
    #         x=0.11,
    #         xanchor="left",
    #         y=1.1,
    #         yanchor="top"
    #     )
    # ]
)
fig.show()

In [ ]:
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Assuming df is already defined with columns: Latitude, Longitude, bulit_area, price_per_sqft, apartment_loc

fig = go.Figure()

# Add scatter points for properties
fig.add_trace(go.Scattermapbox(
    lat=df['Latitude'],
    lon=df['Longitude'],
    mode='markers',
    marker=dict(
        size=filtered_df['bulit_area']/100,
        sizemode='area',
        sizeref=0.1,
        color=filtered_df['price_per_sqft'],
        colorscale='IceFire',
        showscale=True,
        colorbar=dict(title="Price per sqft")
    ),
    text=df['apartment_loc'],
    hoverinfo='text',
    name='Properties'
))

# North Bangalore
north_bangalore_coords = [
    [77.50, 13.17],
    [77.66, 13.14],
    [77.66, 13.03],
    [77.50, 13.03],
    [77.50, 13.17]
]
lons = [coord[0] for coord in north_bangalore_coords]
lats = [coord[1] for coord in north_bangalore_coords]
fig.add_trace(go.Scattermapbox(
    lat=lats,
    lon=lons,
    mode='lines',
    fill='toself',
    fillcolor='rgba(0, 100, 80, 0.2)',
    line=dict(color='rgba(0, 100, 80, 0.8)', width=2),
    name='North Bangalore'
))
fig.add_trace(go.Scattermapbox(
    lat=[13.10],
    lon=[77.58],
    mode='text',
    text=['North Bangalore'],
    textfont=dict(size=14, color='black'),
    showlegend=False
))

# South Bangalore
south_bangalore_coords = [
    [77.52, 12.93],
    [77.68, 12.93],
    [77.68, 12.87],
    [77.52, 12.87],
    [77.52, 12.93]
]
south_lons = [coord[0] for coord in south_bangalore_coords]
south_lats = [coord[1] for coord in south_bangalore_coords]
fig.add_trace(go.Scattermapbox(
    lat=south_lats,
    lon=south_lons,
    mode='lines',
    fill='toself',
    fillcolor='rgba(255, 165, 0, 0.2)',
    line=dict(color='rgba(255, 165, 0, 0.8)', width=2),
    name='South Bangalore'
))
fig.add_trace(go.Scattermapbox(
    lat=[12.90],
    lon=[77.60],
    mode='text',
    text=['South Bangalore'],
    textfont=dict(size=14, color='black'),
    showlegend=False
))

# East Bangalore
east_bangalore_coords = [
    [77.60, 13.02],
    [77.75, 13.02],
    [77.75, 12.92],
    [77.60, 12.92],
    [77.60, 13.02]
]
east_lons = [coord[0] for coord in east_bangalore_coords]
east_lats = [coord[1] for coord in east_bangalore_coords]
fig.add_trace(go.Scattermapbox(
    lat=east_lats,
    lon=east_lons,
    mode='lines',
    fill='toself',
    fillcolor='rgba(138, 43, 226, 0.2)',
    line=dict(color='rgba(138, 43, 226, 0.8)', width=2),
    name='East Bangalore'
))
fig.add_trace(go.Scattermapbox(
    lat=[12.97],
    lon=[77.67],
    mode='text',
    text=['East Bangalore'],
    textfont=dict(size=14, color='black'),
    showlegend=False
))

# West Bangalore
west_bangalore_coords = [
    [77.45, 13.02],
    [77.60, 13.02],
    [77.60, 12.92],
    [77.45, 12.92],
    [77.45, 13.02]
]
west_lons = [coord[0] for coord in west_bangalore_coords]
west_lats = [coord[1] for coord in west_bangalore_coords]
fig.add_trace(go.Scattermapbox(
    lat=west_lats,
    lon=west_lons,
    mode='lines',
    fill='toself',
    fillcolor='rgba(65, 105, 225, 0.2)',
    line=dict(color='rgba(65, 105, 225, 0.8)', width=2),
    name='West Bangalore'
))
fig.add_trace(go.Scattermapbox(
    lat=[12.95],
    lon=[77.56],
    mode='text',
    text=['West Bangalore'],
    textfont=dict(size=14, color='black'),
    showlegend=False
))

# Update layout
fig.update_layout(
    mapbox=dict(
        style="open-street-map",
        center=dict(lat=13.05, lon=77.58),
        zoom=10.5
    ),
    height=700,
    width=1400,
    legend=dict(
        yanchor="top",
        y=0.99,
        xanchor="left",
        x=0.01
    ),
    updatemenus=[
        dict(
            type="buttons",
            direction="left",
            buttons=[
                dict(
                    args=[{"mapbox.zoom": 10.5}],
                    label="Zoom Out",
                    method="relayout"
                ),
                dict(
                    args=[{"mapbox.zoom": 12.2}],
                    label="Zoom In",
                    method="relayout"
                )
            ],
            pad={"r": 10, "t": 10},
            showactive=False,
            x=0.11,
            xanchor="left",
            y=1.1,
            yanchor="top"
        )
    ]
)

fig.show()

In [142]:
merged_df

,zone,bhk_type,construction_status,carpet_area,bulit_area,super_bulit_area,price_value,nearbylocation,facility,luxury_facility_scores,luxury_category,Latitude,Longitude,apartment_name,apartment_loc,price_per_sqft
0,east,1,Under Construction,NaN,668.0,752.84,0.53,"[('mahatma vidhyalaya', '400 m'), ('eterssrt m...","['Yoga/Meditation Area', ""Children's Play Area...",69.0,medium,12.8925,77.7795,Nambiar Millennia,Sarjapur Road,7040.008501
1,east,1,New Property,NaN,431.0,480.00,0.55,"[('soukya road', '1.4 km'), ('mvj college of e...","[""Children's Play Area"", 'Creche/Day Care', 'J...",70.0,medium,12.9955,77.7655,Provident Capella,Samethanahalli,11458.333333
2,east,1,New Property,NaN,619.0,689.00,0.69,"[('one world international school', '3.2kms'),...","['Pet Park', ""Children's Play Area"", 'Landscap...",50.0,medium,13.0155,77.7255,Brigade Citrine Budigere Cross,Byrathi,10014.513788
3,east,1,New Property,NaN,537.0,598.00,0.70,"[('prerana international school', '700 m'), ('...","['Banquet Hall', 'Creche/Day Care', ""Children'...",74.0,medium,13.0468,77.7473,Sattva East Crest Bandapura,Budigere Cross,11705.685619
4,east,1,New Property,486.0,619.0,736.00,0.52,"['Whitefield Kadugodi Metro Station', 'Nexus S...","['Lift(s)', 'Swimming Pool', 'Park', 'Fitness ...",44.0,low,12.9955,77.7655,Sowparnika Columns,Soukya Road,7065.217391
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5340,west,4,Moderatly Old,1800.0,2000.0,2170.00,4.00,"['Mahakavi Kuvempu', 'Orion Mall', 'Christ The...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN,high,12.9985,77.5545,Brigade Gateway,Rajajinagar,18433.179724
5341,west,4,Relatively New,1520.0,1878.0,2171.00,2.50,"['Nagasandra', 'BIEC', 'AH 47', 'Soundarya Art...","['Security / Fire Alarm', 'Power Back-up', 'Fe...",NaN,high,13.0685,77.5925,Prestige Jindal City,Tumkur Road,11515.430677
5342,west,4,Relatively New,2000.0,2200.0,2500.00,3.85,"['Krantiveera Sangolli Rayanna Metro', 'Lulu M...","['Centrally Air Conditioned', 'Water purifier'...",NaN,high,12.9755,77.5555,Prestige West Woods,Okalipuram,15400.000000
5343,west,4,New Property,1429.0,1824.0,2171.00,5.00,"['KSR Metro Station', 'Lulu Mall Bengaluru', '...","['Intercom Facility', 'Lift(s)', 'Separate ent...",NaN,high,12.9985,77.5545,Sobha Rajvilas,Rajajinagar,23030.861354
5344,west,4,Relatively New,2077.0,3037.0,3422.70,2.75,"['Kengeri, Station', 'Gopalan Arcade Mall', 'N...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...",NaN,high,12.9055,77.5355,Lea Sunflower,Kengeri,8034.592573

In [145]:
merged_df.to_csv('appartment_cleaned_final.csv', index=False)

In [146]:
merged_df.dtypes

zone                       object
bhk_type                    int64
construction_status        object
carpet_area               float64
bulit_area                float64
super_bulit_area          float64
price_value               float64
nearbylocation             object
facility                   object
luxury_facility_scores    float64
luxury_category            object
Latitude                  float64
Longitude                 float64
apartment_name             object
apartment_loc              object
price_per_sqft            float64
dtype: object

In [147]:
    # Create columns for better filtering
merged_df['price_range'] = pd.cut(
        merged_df['price_value']* 1e7, 
        bins=[0, 5000000, 10000000, 15000000, 20000000, float('inf')],
        labels=['< 50L', '50L-1Cr', '1Cr-1.5Cr', '1.5Cr-2Cr', '> 2Cr']
    )

In [155]:
merged_df['area_range'] = pd.cut(
        merged_df['bulit_area'],
        bins=[0, 1000, 1500, 2000, 2500, float('inf')],
        labels=['< 1000 sqft', '1000-1500 sqft', '1500-2000 sqft', '2000-2500 sqft', '> 2500 sqft'])

In [156]:
merged_df.to_csv('appartment_cleaned_final.csv', index=False)