In [1]:
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer, KNNImputer, MissingIndicator
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder, MinMaxScaler, PowerTransformer, OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from lightgbm import LGBMRegressor
from pathlib import Path

In [2]:
import dagshub
dagshub.init(repo_owner='AMR-ITH', repo_name='RealEstateInsights', mlflow=True)
import mlflow

# set the tracking server

mlflow.set_tracking_uri("https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow")

# mlflow experiment

mlflow.set_experiment("Exp 3 - RF-HP Tuning-30")

Accessing as AMR-ITH

Initialized MLflow to track repo "AMR-ITH/RealEstateInsights"

Repository AMR-ITH/RealEstateInsights initialized!

<Experiment: artifact_location='mlflow-artifacts:/977cb1ccd3cd4a8198e4876b6a083c11', creation_time=1746527225080, experiment_id='5', last_update_time=1746527225080, lifecycle_stage='active', name='Exp 3 - RF-HP Tuning-30', tags={}>

In [4]:
# pathlib is a module in Python that provides an object-oriented interface 
# for working with file system paths.
current = Path.cwd()
parent = current.parent

# load the data 
df = pd.read_csv(parent /'data-scraped/interim_data.csv')
df.head()

,apartment_name,appartment_loc,zone,bhk_type,construction_status,carpet_area,bulit_area,super_bulit_area,price_value,nearbylocation,facility,luxury_facility_scores
0,nambiar millennia,Sarjapur Road,east,1,Under Construction,NaN,668.0,NaN,0.53,"[('mahatma vidhyalaya', '400 m'), ('eterssrt m...","['Yoga/Meditation Area', ""Children's Play Area...",69
1,provident capella,Samethanahalli,east,1,New Property,NaN,431.0,480.0,0.55,"[('soukya road', '1.4 km'), ('mvj college of e...","[""Children's Play Area"", 'Creche/Day Care', 'J...",70
2,brigade citre budigere cross,Byrathi,east,1,New Property,NaN,619.0,689.0,0.69,"[('one world international school', '3.2kms'),...","['Pet Park', ""Children's Play Area"", 'Landscap...",50
3,sattva east crest bandapura,Budigere Cross,east,1,New Property,NaN,537.0,598.0,0.70,"[('prerana international school', '700 m'), ('...","['Banquet Hall', 'Creche/Day Care', ""Children'...",74
4,sowparnika columns,Soukya Road,east,1,New Property,486.0,619.0,736.0,0.52,"['Whitefield Kadugodi Metro Station', 'Nexus S...","['Lift(s)', 'Swimming Pool', 'Park', 'Fitness ...",44

In [5]:
def categorize_luxury(score):
    if 0 <= score < 50:
        return 'low'
    elif 50 <= score < 150:
        return 'medium'
    else:
        return 'high'
    
df['luxury_category'] = df['luxury_facility_scores'].apply(categorize_luxury)

In [6]:
df.drop(columns=['carpet_area','super_bulit_area','nearbylocation','facility','apartment_name','appartment_loc','luxury_facility_scores'], inplace=True)

In [7]:
temp_df = df.copy()

X = temp_df.drop(columns=['price_value'])
y = temp_df['price_value']

In [8]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
# do the basic processing input data

num_cols = ['bulit_area']
nomial_cols = ['zone']
ordinal_cols = ['construction_status','bhk_type','luxury_category']

In [10]:
bhk_type_order = ['1','2','3','4','5','6','7','8','9','10']
construction_status_order = ['New Property','Under Construction', 'Relatively New', 'Moderatly Old', 'Old','undefined']
luxury_facility_scores_order = ['low','medium','high']

In [11]:
# build a preprocessor

prepocessor = ColumnTransformer(transformers=[
    ("scale", MinMaxScaler(), num_cols),
        ("nominal_encode", OneHotEncoder(handle_unknown="ignore",sparse_output=False), nomial_cols),
    ("ordinal_encode", OrdinalEncoder(categories=[construction_status_order,bhk_type_order,luxury_facility_scores_order]), ordinal_cols)
],remainder="passthrough",n_jobs=-1,force_int_remainder_cols=False,verbose_feature_names_out=False)

prepocessor.set_output(transform="pandas")

ColumnTransformer(force_int_remainder_cols=False, n_jobs=-1,
                  remainder='passthrough',
                  transformers=[('scale', MinMaxScaler(), ['bulit_area']),
                                ('nominal_encode',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 ['zone']),
                                ('ordinal_encode',
                                 OrdinalEncoder(categories=[['New Property',
                                                             'Under '
                                                             'Construction',
                                                             'Relatively New',
                                                             'Moderatly Old',
                                                             'Old',
                                                             'undefined'],
                                                            ['1', '2', '3', '4',
                                                             '5', '6', '7', '8',
                                                             '9', '10'],
                                                            ['low', 'medium',
                                                             'high']]),
                                 ['construction_status', 'bhk_type',
                                  'luxury_category'])],
                  verbose_feature_names_out=False)

In [12]:
# transform the data

X_train_trans = prepocessor.fit_transform(X_train)
X_test_trans = prepocessor.transform(X_test)

X_train_trans

,bulit_area,zone_east,zone_north,zone_south,zone_west,construction_status,bhk_type,luxury_category
2842,0.197885,0.0,1.0,0.0,0.0,0.0,2.0,1.0
903,0.185153,1.0,0.0,0.0,0.0,2.0,2.0,1.0
3262,0.297475,0.0,1.0,0.0,0.0,2.0,2.0,1.0
109,0.114804,1.0,0.0,0.0,0.0,1.0,1.0,1.0
5602,0.092361,0.0,0.0,0.0,1.0,5.0,1.0,0.0
...,...,...,...,...,...,...,...,...
3772,0.224860,0.0,1.0,0.0,0.0,0.0,3.0,1.0
5191,0.140160,0.0,0.0,1.0,0.0,0.0,2.0,1.0
5226,0.175874,0.0,0.0,1.0,0.0,4.0,2.0,1.0
5390,0.118041,0.0,0.0,0.0,1.0,2.0,1.0,1.0
860,0.139189,1.0,0.0,0.0,0.0,0.0,2.0,0.0

In [13]:
from sklearn.ensemble import RandomForestRegressor
import optuna

from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.model_selection import cross_val_score

c:\Python\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [50]:
import matplotlib.pyplot as plt
from lightgbm import LGBMRegressor
import time

In [24]:


def objective(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 500),
        "max_depth": trial.suggest_int("max_depth", 3, 50),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3),
        "num_leaves": trial.suggest_int("num_leaves", 20, 150),
        "min_child_samples": trial.suggest_int("min_child_samples", 5, 100),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 0.0, 10.0),
        "reg_lambda": trial.suggest_float("reg_lambda", 0.0, 10.0),
        "random_state": 42,
        "n_jobs": -1,
    }
    
    # build the model
    lgbm = LGBMRegressor(**params)
    
    # train the model
    lgbm.fit(X_train_trans, y_train)
    
    # get the predictions
    y_pred_train = lgbm.predict(X_train_trans)
    y_pred_test = lgbm.predict(X_test_trans)

    
    # Calculate metrics
    mae_test = mean_absolute_error(y_test, y_pred_test)
    r2_test = r2_score(y_test, y_pred_test)

    # perform cross validation for MAE
    cv_mae_scores_train = cross_val_score(
        lgbm,
        X_train_trans,
        y_train,
        cv=5,
        scoring="neg_mean_absolute_error",
        n_jobs=-1
    )
    
    cv_mae_scores_test = cross_val_score(
        lgbm,
        X_test_trans,
        y_test,
        cv=5,
        scoring="neg_mean_absolute_error",
        n_jobs=-1
    )
    
    # perform cross validation for R2
    cv_r2_scores_train = cross_val_score(
        lgbm,
        X_train_trans,
        y_train,
        cv=5,
        scoring="r2",
        n_jobs=-1
    )

    cv_r2_scores_test = cross_val_score(
        lgbm,
        X_test_trans,
        y_test,
        cv=5,
        scoring="r2",
        n_jobs=-1
    )
    
    
    # mean scores from cross-validation train
    mean_cv_mae_train = -cv_mae_scores_train.mean()
    mean_cv_r2_train = cv_r2_scores_train.mean()

    mean_cv_mae_test = -cv_mae_scores_test.mean()
    mean_cv_r2_test = cv_r2_scores_test.mean() 
    print("train mae",mean_cv_mae_train)
    print("train r2",mean_cv_r2_train)

    print("test mae",mean_cv_mae_test)
    print("test r2",mean_cv_r2_test)   
    
    # Store metrics in trial user attributes for display
    trial.set_user_attr("mae_test", mae_test)
    trial.set_user_attr("r2_test", r2_test)
    trial.set_user_attr("cv_mae_train", mean_cv_mae_train)
    trial.set_user_attr("cv_r2_train", mean_cv_r2_train)
    trial.set_user_attr("cv_mae_test",mean_cv_mae_test)
    trial.set_user_attr("cv_mae_test",mean_cv_r2_test)
    
    # Combined score - we want to minimize MAE and maximize R2
    # Lower value is better
    combined_score = mae_test / (1 + max(0, r2_test))
    
    return combined_score

In [27]:
# optimize the objective function
study.optimize(objective, n_trials=30, n_jobs=-1, show_progress_bar=True)

Best trial: 17. Best value: 0.250019:   3%|▎         | 1/30 [00:35<17:07, 35.41s/it]

train mae 0.5179493878254922
train r2 0.7919859618000679
test mae 0.5687820078189965
test r2 0.7438664323126739
[I 2025-05-08 17:50:05,940] Trial 43 finished with value: 0.27331670053544543 and parameters: {'n_estimators': 182, 'max_depth': 36, 'learning_rate': 0.08623651551553785, 'num_leaves': 58, 'min_child_samples': 92, 'subsample': 0.5023564016642542, 'colsample_bytree': 0.7816565741300607, 'reg_alpha': 7.6098046169437215, 'reg_lambda': 9.07841121226063}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019:   7%|▋         | 2/30 [00:36<07:00, 15.03s/it]

train mae 0.5129678565698365
train r2 0.7974721649444667
test mae 0.553117137699578
test r2 0.7620264981756553
[I 2025-05-08 17:50:06,715] Trial 48 finished with value: 0.26722258747500877 and parameters: {'n_estimators': 186, 'max_depth': 37, 'learning_rate': 0.15293223632802871, 'num_leaves': 111, 'min_child_samples': 49, 'subsample': 0.5645163953925569, 'colsample_bytree': 0.7865228480056493, 'reg_alpha': 9.250632056947799, 'reg_lambda': 4.172941880283828}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019:  10%|█         | 3/30 [00:37<04:00,  8.90s/it]

train mae 0.5183452300505892
train r2 0.7918430060135808
test mae 0.5642394342076613
test r2 0.746489670713604
[I 2025-05-08 17:50:08,323] Trial 53 finished with value: 0.27344504722872864 and parameters: {'n_estimators': 193, 'max_depth': 37, 'learning_rate': 0.1152784033248245, 'num_leaves': 63, 'min_child_samples': 91, 'subsample': 0.5845696120690704, 'colsample_bytree': 0.743592001711995, 'reg_alpha': 9.355532092747403, 'reg_lambda': 1.8803026648292342}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019:  13%|█▎        | 4/30 [00:39<02:35,  5.99s/it]

train mae 0.5132952220458866
train r2 0.7947359225572355
test mae 0.5607283190719906
test r2 0.7496227046872954
[I 2025-05-08 17:50:09,843] Trial 50 finished with value: 0.2711427820924183 and parameters: {'n_estimators': 191, 'max_depth': 37, 'learning_rate': 0.06542802051360895, 'num_leaves': 25, 'min_child_samples': 84, 'subsample': 0.8438033343645, 'colsample_bytree': 0.892622401457885, 'reg_alpha': 5.161909002446401, 'reg_lambda': 5.562815355405748}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019:  17%|█▋        | 5/30 [00:40<01:49,  4.38s/it]

train mae 0.5107607483547527
train r2 0.7969058738915333
test mae 0.5525220884282523
test r2 0.7592294999908542
[I 2025-05-08 17:50:11,373] Trial 42 finished with value: 0.27054245575018365 and parameters: {'n_estimators': 184, 'max_depth': 38, 'learning_rate': 0.044406842549728945, 'num_leaves': 70, 'min_child_samples': 67, 'subsample': 0.639946924337696, 'colsample_bytree': 0.7790182268297737, 'reg_alpha': 3.439973078516157, 'reg_lambda': 5.077464639571895}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019:  20%|██        | 6/30 [00:41<01:13,  3.08s/it]

train mae 0.5112661814926488
train r2 0.7968383742374089
test mae 0.5543111190118053
test r2 0.7584105745482267
[I 2025-05-08 17:50:11,924] Trial 47 finished with value: 0.2705222298171387 and parameters: {'n_estimators': 180, 'max_depth': 35, 'learning_rate': 0.04390922551103228, 'num_leaves': 94, 'min_child_samples': 72, 'subsample': 0.5237771304510845, 'colsample_bytree': 0.8127283184542606, 'reg_alpha': 4.060998591474665, 'reg_lambda': 3.6290476601582284}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019:  23%|██▎       | 7/30 [00:42<00:57,  2.51s/it]

train mae 0.5142389888816842
train r2 0.7954154015228023
test mae 0.5527551374703161
test r2 0.7576042194252268
[I 2025-05-08 17:50:13,278] Trial 45 finished with value: 0.2753472962334736 and parameters: {'n_estimators': 184, 'max_depth': 36, 'learning_rate': 0.028465231206361574, 'num_leaves': 150, 'min_child_samples': 69, 'subsample': 0.8089548893756294, 'colsample_bytree': 0.9005449399401475, 'reg_alpha': 2.421327106567995, 'reg_lambda': 8.997298819617432}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019:  27%|██▋       | 8/30 [00:45<00:58,  2.65s/it]

train mae 0.5092231263511308
train r2 0.793465476127128
test mae 0.5496215233224292
test r2 0.7588849526687779
[I 2025-05-08 17:50:16,205] Trial 52 finished with value: 0.26588065510912207 and parameters: {'n_estimators': 182, 'max_depth': 35, 'learning_rate': 0.18343950737508202, 'num_leaves': 60, 'min_child_samples': 52, 'subsample': 0.5743686462537599, 'colsample_bytree': 0.9106039836835161, 'reg_alpha': 3.897626418421826, 'reg_lambda': 8.030100727739839}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019:  30%|███       | 9/30 [00:52<01:21,  3.86s/it]

train mae 0.5140999770119153
train r2 0.7856356235425516
test mae 0.554465870276604
test r2 0.7562279249264903
[I 2025-05-08 17:50:22,745] Trial 46 finished with value: 0.2770067677233639 and parameters: {'n_estimators': 187, 'max_depth': 36, 'learning_rate': 0.1995794823680346, 'num_leaves': 60, 'min_child_samples': 9, 'subsample': 0.6383188968951685, 'colsample_bytree': 0.7644441779134892, 'reg_alpha': 1.84864788846426, 'reg_lambda': 9.511707208220901}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019:  33%|███▎      | 10/30 [00:52<00:57,  2.85s/it]

train mae 0.5169230216637904
train r2 0.7886428096050612
test mae 0.5456611284083225
test r2 0.7671551557307226
[I 2025-05-08 17:50:23,330] Trial 51 finished with value: 0.2717965511828576 and parameters: {'n_estimators': 186, 'max_depth': 50, 'learning_rate': 0.1922002734865209, 'num_leaves': 95, 'min_child_samples': 35, 'subsample': 0.9333619934023483, 'colsample_bytree': 0.8677615185907175, 'reg_alpha': 1.3324200204357162, 'reg_lambda': 5.778654068886922}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019:  37%|███▋      | 11/30 [00:53<00:42,  2.23s/it]

train mae 0.5120526011177693
train r2 0.793494652353435
test mae 0.5523744596871693
test r2 0.7579570631654143
[I 2025-05-08 17:50:24,141] Trial 44 finished with value: 0.26781552130796665 and parameters: {'n_estimators': 375, 'max_depth': 37, 'learning_rate': 0.10423484510864192, 'num_leaves': 130, 'min_child_samples': 62, 'subsample': 0.8578598281850368, 'colsample_bytree': 0.7983128701012735, 'reg_alpha': 1.9024733814449046, 'reg_lambda': 9.893548557284184}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019:  40%|████      | 12/30 [01:00<01:04,  3.60s/it]

train mae 0.5245737379216304
train r2 0.776001629099951
test mae 0.5511484161627165
test r2 0.7524775134682746
[I 2025-05-08 17:50:30,873] Trial 49 finished with value: 0.28918452698896446 and parameters: {'n_estimators': 184, 'max_depth': 37, 'learning_rate': 0.1898238874487117, 'num_leaves': 108, 'min_child_samples': 6, 'subsample': 0.8968736804384152, 'colsample_bytree': 0.7878167299601336, 'reg_alpha': 1.275833343928353, 'reg_lambda': 0.3518437779292434}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019:  43%|████▎     | 13/30 [02:05<06:17, 22.21s/it]

train mae 0.5336677212016105
train r2 0.7700394310435801
test mae 0.5677027252349103
test r2 0.7392981694042695
[I 2025-05-08 17:51:35,916] Trial 61 finished with value: 0.2881039035062856 and parameters: {'n_estimators': 90, 'max_depth': 26, 'learning_rate': 0.29464877911206167, 'num_leaves': 148, 'min_child_samples': 9, 'subsample': 0.9988575330764862, 'colsample_bytree': 0.5581012544748404, 'reg_alpha': 0.768987992293062, 'reg_lambda': 0.3153348027852072}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019:  47%|████▋     | 14/30 [02:09<04:30, 16.88s/it]

train mae 0.5118721660969033
train r2 0.7932694565696414
test mae 0.5385559373452307
test r2 0.7751897114525372
[I 2025-05-08 17:51:40,463] Trial 63 finished with value: 0.2663935815933483 and parameters: {'n_estimators': 225, 'max_depth': 26, 'learning_rate': 0.29765138438861094, 'num_leaves': 141, 'min_child_samples': 5, 'subsample': 0.9812838048971781, 'colsample_bytree': 0.5007321152558628, 'reg_alpha': 6.3922175199581, 'reg_lambda': 0.8843644032582372}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019:  50%|█████     | 15/30 [02:17<03:32, 14.18s/it]

train mae 0.5149847120619587
train r2 0.7900488233621343
test mae 0.5410515457069816
test r2 0.7760952305846182
[I 2025-05-08 17:51:48,372] Trial 64 finished with value: 0.2703200393888373 and parameters: {'n_estimators': 218, 'max_depth': 26, 'learning_rate': 0.2896074310086505, 'num_leaves': 38, 'min_child_samples': 9, 'subsample': 0.9750536982941183, 'colsample_bytree': 0.5099058466031592, 'reg_alpha': 6.0303341151690955, 'reg_lambda': 0.8906257480754087}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019:  53%|█████▎    | 16/30 [02:27<03:00, 12.88s/it]

train mae 0.5144106598512952
train r2 0.7952985698586309
test mae 0.5479507597240889
test r2 0.7713353001744515
[I 2025-05-08 17:51:58,242] Trial 65 finished with value: 0.2699326866260158 and parameters: {'n_estimators': 232, 'max_depth': 27, 'learning_rate': 0.29509109473230577, 'num_leaves': 22, 'min_child_samples': 27, 'subsample': 0.7432831005190869, 'colsample_bytree': 0.5037004859057292, 'reg_alpha': 6.446054822671288, 'reg_lambda': 7.14299421743223}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019:  57%|█████▋    | 17/30 [02:28<02:01,  9.36s/it]

train mae 0.5472549927679085
train r2 0.7608846358522673
test mae 0.583744696176997
test r2 0.727400049543679
[I 2025-05-08 17:51:59,436] Trial 56 finished with value: 0.29266859163983566 and parameters: {'n_estimators': 236, 'max_depth': 26, 'learning_rate': 0.2992552939265434, 'num_leaves': 149, 'min_child_samples': 8, 'subsample': 0.9968783030598811, 'colsample_bytree': 0.5104526402310974, 'reg_alpha': 0.3149196417536517, 'reg_lambda': 9.662066248713387}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019:  60%|██████    | 18/30 [02:33<01:36,  8.08s/it]

train mae 0.5610165386672543
train r2 0.7450538989737898
test mae 0.5997115466336382
test r2 0.709028552016519
[I 2025-05-08 17:52:04,531] Trial 55 finished with value: 0.3142592213744175 and parameters: {'n_estimators': 231, 'max_depth': 25, 'learning_rate': 0.2874320556191897, 'num_leaves': 149, 'min_child_samples': 5, 'subsample': 0.971939576391432, 'colsample_bytree': 0.5114604891719039, 'reg_alpha': 0.18915290978581822, 'reg_lambda': 0.5288715882828097}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019:  63%|██████▎   | 19/30 [02:35<01:05,  5.99s/it]

train mae 0.5627385973044582
train r2 0.7430939122649544
test mae 0.6045665887941756
test r2 0.7037073650202013
[I 2025-05-08 17:52:05,643] Trial 54 finished with value: 0.3090672944971648 and parameters: {'n_estimators': 231, 'max_depth': 47, 'learning_rate': 0.2658365366328595, 'num_leaves': 150, 'min_child_samples': 5, 'subsample': 0.9963685183706376, 'colsample_bytree': 0.5156659573913329, 'reg_alpha': 0.021481156562127346, 'reg_lambda': 0.617838074573589}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019:  67%|██████▋   | 20/30 [02:36<00:46,  4.68s/it]

train mae 0.5487257050761435
train r2 0.7579914120037798
test mae 0.5883791081268296
test r2 0.7190563405764931
[I 2025-05-08 17:52:07,272] Trial 60 finished with value: 0.29649003756891634 and parameters: {'n_estimators': 236, 'max_depth': 50, 'learning_rate': 0.2938434451802727, 'num_leaves': 146, 'min_child_samples': 11, 'subsample': 0.981989435182766, 'colsample_bytree': 0.526973270808466, 'reg_alpha': 0.6983453613028869, 'reg_lambda': 0.07824318218308957}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019:  70%|███████   | 21/30 [02:38<00:33,  3.68s/it]

train mae 0.5612768898815934
train r2 0.7506661819175543
test mae 0.5989232939216527
test r2 0.7241110610484638
[I 2025-05-08 17:52:08,612] Trial 58 finished with value: 0.31091760131564167 and parameters: {'n_estimators': 241, 'max_depth': 25, 'learning_rate': 0.296995669717533, 'num_leaves': 146, 'min_child_samples': 8, 'subsample': 0.9028907899397405, 'colsample_bytree': 0.5680807258732451, 'reg_alpha': 0.5103574552493253, 'reg_lambda': 0.08437982039108327}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019:  73%|███████▎  | 22/30 [02:40<00:26,  3.34s/it]

train mae 0.5592701333450277
train r2 0.7569335899660266
test mae 0.5953669123070698
test r2 0.732521227220729
[I 2025-05-08 17:52:11,157] Trial 59 finished with value: 0.3031706813459706 and parameters: {'n_estimators': 237, 'max_depth': 48, 'learning_rate': 0.2991593341286646, 'num_leaves': 138, 'min_child_samples': 11, 'subsample': 0.9767066633682342, 'colsample_bytree': 0.5829468678753715, 'reg_alpha': 0.2829420562335656, 'reg_lambda': 9.799236388842196}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019:  77%|███████▋  | 23/30 [02:42<00:20,  2.95s/it]

train mae 0.5424163977629147
train r2 0.7555119636774594
test mae 0.5707387246998221
test r2 0.7348257383745354
[I 2025-05-08 17:52:13,199] Trial 62 finished with value: 0.2898957619309179 and parameters: {'n_estimators': 237, 'max_depth': 27, 'learning_rate': 0.272746464985594, 'num_leaves': 142, 'min_child_samples': 5, 'subsample': 0.9876086189887832, 'colsample_bytree': 0.5509974507815141, 'reg_alpha': 0.7930021718042486, 'reg_lambda': 0.8584815918289603}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019:  80%|████████  | 24/30 [02:43<00:13,  2.21s/it]

train mae 0.5701522013550766
train r2 0.7405054974224766
test mae 0.6118590113930151
test r2 0.6951637888863653
[I 2025-05-08 17:52:13,688] Trial 57 finished with value: 0.31240489929350623 and parameters: {'n_estimators': 238, 'max_depth': 46, 'learning_rate': 0.2974009238616036, 'num_leaves': 148, 'min_child_samples': 8, 'subsample': 0.9965866809810439, 'colsample_bytree': 0.5265077421501627, 'reg_alpha': 0.07636332157464842, 'reg_lambda': 0.12315722906287263}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019:  83%|████████▎ | 25/30 [02:46<00:12,  2.45s/it]

train mae 0.5106958031020711
train r2 0.7941573099225163
test mae 0.5485849951650016
test r2 0.7692265629617434
[I 2025-05-08 17:52:16,700] Trial 66 finished with value: 0.2692716480927519 and parameters: {'n_estimators': 227, 'max_depth': 21, 'learning_rate': 0.29891378285595804, 'num_leaves': 25, 'min_child_samples': 26, 'subsample': 0.7259167908888806, 'colsample_bytree': 0.9940017718800169, 'reg_alpha': 6.632717605056191, 'reg_lambda': 7.386301836831802}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019:  87%|████████▋ | 26/30 [02:46<00:07,  1.78s/it]

train mae 0.5119955714918782
train r2 0.7993199813282864
test mae 0.5511627540937183
test r2 0.7721677775158866
[I 2025-05-08 17:52:16,929] Trial 67 finished with value: 0.26547161555709603 and parameters: {'n_estimators': 223, 'max_depth': 14, 'learning_rate': 0.2558616645602224, 'num_leaves': 38, 'min_child_samples': 28, 'subsample': 0.7265719988169806, 'colsample_bytree': 0.660789513692106, 'reg_alpha': 7.595394877398239, 'reg_lambda': 7.238217330380452}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019:  93%|█████████▎| 28/30 [02:46<00:02,  1.01s/it]

train mae 0.5129033894240589
train r2 0.7996123303271319
test mae 0.5517374797729705
test r2 0.7698413911712352
[I 2025-05-08 17:52:17,340] Trial 68 finished with value: 0.26785785107737636 and parameters: {'n_estimators': 237, 'max_depth': 14, 'learning_rate': 0.23079551976639556, 'num_leaves': 21, 'min_child_samples': 27, 'subsample': 0.7693401402078017, 'colsample_bytree': 0.6586737811824726, 'reg_alpha': 7.6963017286613695, 'reg_lambda': 6.806496310417832}. Best is trial 17 with value: 0.2500185449653238.
train mae 0.5072023165036408
train r2 0.7991239366872576
test mae 0.5487592362475564
test r2 0.7687400537561336
[I 2025-05-08 17:52:17,508] Trial 69 finished with value: 0.26754319197246074 and parameters: {'n_estimators': 152, 'max_depth': 14, 'learning_rate': 0.23695331193503777, 'num_leaves': 125, 'min_child_samples': 30, 'subsample': 0.7396294112062634, 'colsample_bytree': 0.9898738663577338, 'reg_alpha': 8.380933379749257, 'reg_lambda': 2.6596428774273475}. Best is trial 17 with value: 0.2500185449653238.

Best trial: 17. Best value: 0.250019: 100%|██████████| 30/30 [02:47<00:00,  5.58s/it]

train mae 0.5186736349126139
train r2 0.7908219947254413
test mae 0.5745016021240866
test r2 0.7384776716590205
[I 2025-05-08 17:52:17,610] Trial 70 finished with value: 0.27305202538528855 and parameters: {'n_estimators': 144, 'max_depth': 14, 'learning_rate': 0.24966539755716194, 'num_leaves': 42, 'min_child_samples': 100, 'subsample': 0.7358594973106954, 'colsample_bytree': 0.6487520187942994, 'reg_alpha': 8.39196852645544, 'reg_lambda': 2.608606897298494}. Best is trial 17 with value: 0.2500185449653238.
train mae 0.5209396945602824
train r2 0.7913015933121736
test mae 0.5775696247957247
test r2 0.7375239281893241
[I 2025-05-08 17:52:17,782] Trial 71 finished with value: 0.27555232657176415 and parameters: {'n_estimators': 149, 'max_depth': 21, 'learning_rate': 0.24081678333638917, 'num_leaves': 44, 'min_child_samples': 100, 'subsample': 0.7439673762853298, 'colsample_bytree': 0.6871293612447112, 'reg_alpha': 9.89176992007244, 'reg_lambda': 3.1397824907765957}. Best is trial 17 with value: 0.2500185449653238.

In [28]:
# train the model on best parameters
best_rf = LGBMRegressor(**study.best_params)

best_rf.fit(X_train_trans,y_train)

y_pred_train = best_rf.predict(X_train_trans)
y_pred_test = best_rf.predict(X_test_trans)



scores = cross_val_score(best_rf,X_train_trans,y_train,cv=5,n_jobs=-1)

# mae,r2 for test and train
mae_train = mean_absolute_error(y_train,y_pred_train)
r2_train = r2_score(y_train,y_pred_train)
mae_test = mean_absolute_error(y_test,y_pred_test)
r2_test = r2_score(y_test,y_pred_test)


print(mae_train)
print(r2_train)
print(mae_test)
print(r2_test)

[LightGBM] [Warning] Unknown parameter: max_samples
[LightGBM] [Warning] Unknown parameter: max_features
[LightGBM] [Warning] Unknown parameter: min_samples_split
[LightGBM] [Warning] min_data_in_leaf is set with min_child_samples=20, will be overridden by min_samples_leaf=1. Current value: min_data_in_leaf=1
[LightGBM] [Warning] Unknown parameter: bootstrap
[LightGBM] [Warning] Unknown parameter: max_samples
[LightGBM] [Warning] Unknown parameter: max_features
[LightGBM] [Warning] Unknown parameter: min_samples_split
[LightGBM] [Warning] min_data_in_leaf is set with min_child_samples=20, will be overridden by min_samples_leaf=1. Current value: min_data_in_leaf=1
[LightGBM] [Warning] Unknown parameter: bootstrap
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000371 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 470
[LightGBM] [Info] Number of data points in the train set: 4860, number of used features: 8
[LightGBM] [Info] Start training from score 1.964580
[LightGBM] [Warning] Unknown parameter: max_samples
[LightGBM] [Warning] Unknown parameter: max_features
[LightGBM] [Warning] Unknown parameter: min_samples_split
[LightGBM] [Warning] min_data_in_leaf is set with min_child_samples=20, will be overridden by min_samples_leaf=1. Current value: min_data_in_leaf=1
[LightGBM] [Warning] Unknown parameter: bootstrap
[LightGBM] [Warning] Unknown parameter: max_samples
[LightGBM] [Warning] Unknown parameter: max_features
[LightGBM] [Warning] Unknown parameter: min_samples_split
[LightGBM] [Warning] min_data_in_leaf is set with min_child_samples=20, will be overridden by min_samples_leaf=1. Current value: min_data_in_leaf=1
[LightGBM] [Warning] Unknown parameter: bootstrap
0.2429961566031077
0.9687865484700526
0.48380086117659543
0.7960924760844564

In [18]:
study.best_params

{'n_estimators': 150,
 'max_depth': 25,
 'learning_rate': 0.22571315117777171,
 'num_leaves': 94,
 'min_child_samples': 48,
 'subsample': 0.7859608525116539,
 'colsample_bytree': 0.6713298072955733,
 'reg_alpha': 2.9441365937007995,
 'reg_lambda': 8.073108740850945}

In [19]:
def objective(trial):
    with mlflow.start_run(nested=True):
        params = {
            "n_estimators": trial.suggest_int("n_estimators", 10, 500),
            "max_depth": trial.suggest_int("max_depth", 1, 30),
            "max_features": trial.suggest_categorical("max_features", [None, "sqrt", "log2"]),
            "min_samples_split": trial.suggest_int("min_samples_split", 2, 10),
            "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 10),
            "max_samples": trial.suggest_float("max_samples", 0.5, 1),
            "bootstrap": trial.suggest_categorical("bootstrap", [True]),  # Always True if using max_samples
            "random_state": 42,
            "n_jobs": -1,
        }

        # Log hyperparameters
        mlflow.log_params(params)

        # Build and train the model
        rf = RandomForestRegressor(**params)
        rf.fit(X_train_trans, y_train)

        # Predictions
        y_pred_train = rf.predict(X_train_trans)
        y_pred_test = rf.predict(X_test_trans)

        # Basic evaluation
        mae_test = mean_absolute_error(y_test, y_pred_test)
        r2_test = r2_score(y_test, y_pred_test)

        # Cross-validation on train data
        cv_mae_scores_train = cross_val_score(
            rf, X_train_trans, y_train, cv=5,
            scoring="neg_mean_absolute_error", n_jobs=-1
        )
        cv_r2_scores_train = cross_val_score(
            rf, X_train_trans, y_train, cv=5,
            scoring="r2", n_jobs=-1
        )

        # Cross-validation on test data (optional, but included for insight)
        cv_mae_scores_test = cross_val_score(
            rf, X_test_trans, y_test, cv=5,
            scoring="neg_mean_absolute_error", n_jobs=-1
        )
        cv_r2_scores_test = cross_val_score(
            rf, X_test_trans, y_test, cv=5,
            scoring="r2", n_jobs=-1
        )

        # Compute means
        mean_cv_mae_train = -cv_mae_scores_train.mean()
        mean_cv_r2_train = cv_r2_scores_train.mean()
        mean_cv_mae_test = -cv_mae_scores_test.mean()
        mean_cv_r2_test = cv_r2_scores_test.mean()

        # Log metrics
        mlflow.log_metric("cv_mae_train", mean_cv_mae_train)
        mlflow.log_metric("cv_r2_train", mean_cv_r2_train)
        mlflow.log_metric("cv_mae_test", mean_cv_mae_test)
        mlflow.log_metric("cv_r2_test", mean_cv_r2_test)
        mlflow.log_metric("test_mae", mae_test)
        mlflow.log_metric("test_r2", r2_test)

        # Print for tracking
        print("train mae:", mean_cv_mae_train)
        print("train r2:", mean_cv_r2_train)
        print("test mae:", mean_cv_mae_test)
        print("test r2:", mean_cv_r2_test)

        # Store Optuna user attributes
        trial.set_user_attr("mae_test", mae_test)
        trial.set_user_attr("r2_test", r2_test)
        trial.set_user_attr("cv_mae_train", mean_cv_mae_train)
        trial.set_user_attr("cv_r2_train", mean_cv_r2_train)
        trial.set_user_attr("cv_mae_test", mean_cv_mae_test)
        trial.set_user_attr("cv_r2_test", mean_cv_r2_test)

        # Final score to minimize
        # combined_score = mae_test / (1 + max(0, r2_test))
        # mlflow.log_metric("combined_score", combined_score)

        return mean_cv_mae_test

In [20]:
import optuna

In [21]:
# import mlflow

study = optuna.create_study(direction="minimize")

with mlflow.start_run(run_name="best_model"):
    # optimize the objective function
    study.optimize(objective,n_trials=30,n_jobs=-1,show_progress_bar=True)

    # log the best parameters
    mlflow.log_params(study.best_params)

    # log the best score
    mlflow.log_metric("best_score",study.best_value)

    # train the model on best parameters
    best_rf = RandomForestRegressor(**study.best_params)

    best_rf.fit(X_train_trans,y_train)

    y_pred_train = best_rf.predict(X_train_trans)
    y_pred_test = best_rf.predict(X_test_trans)
    mlflow.sklearn.log_model(best_rf,"model")
    mlflow.log_params(best_rf.get_params())


    scores = cross_val_score(best_rf,X_train_trans,y_train,cv=5,n_jobs=-1)

    # mae,r2 for test and train
    mae_train = mean_absolute_error(y_train,y_pred_train)
    r2_train = r2_score(y_train,y_pred_train)
    mae_test = mean_absolute_error(y_test,y_pred_test)
    r2_test = r2_score(y_test,y_pred_test)

    mlflow.log_metric("mae-train",mae_train)
    mlflow.log_metric("r2-train",r2_train)
    mlflow.log_metric("mae-test",mae_test)
    mlflow.log_metric("r2-test",r2_test)

        # log the best model
    mlflow.sklearn.log_model(best_rf,artifact_path="model")

[I 2025-05-12 09:23:15,378] A new study created in memory with name: no-name-3c036d98-86d0-4ab0-a35f-cb2eda34a863
  0%|          | 0/30 [00:00<?, ?it/s]

train mae: 0.5270438662039435
train r2: 0.7864051502243737
test mae: 0.5752248226028305
test r2: 0.7424697166959036
train mae: 0.5058707208825063
train r2: 0.7977605567912323
test mae: 0.5301734856591336
test r2: 0.7802234666893904
🏃 View run vaunted-hog-614 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/bca44ea928b14fc88e2fab9524f9ff10
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5
🏃 View run overjoyed-skink-385 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/8cacd35108cd4024a19db6e623c922f7
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5

Best trial: 1. Best value: 0.575225:   3%|▎         | 1/30 [00:29<14:02, 29.06s/it]

[I 2025-05-12 09:23:44,794] Trial 1 finished with value: 0.5752248226028305 and parameters: {'n_estimators': 245, 'max_depth': 12, 'max_features': 'sqrt', 'min_samples_split': 7, 'min_samples_leaf': 9, 'max_samples': 0.8997223324574495, 'bootstrap': True}. Best is trial 1 with value: 0.5752248226028305.

Best trial: 0. Best value: 0.530173:   7%|▋         | 2/30 [00:29<05:50, 12.52s/it]

[I 2025-05-12 09:23:45,728] Trial 0 finished with value: 0.5301734856591336 and parameters: {'n_estimators': 124, 'max_depth': 15, 'max_features': 'log2', 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_samples': 0.6598771107289048, 'bootstrap': True}. Best is trial 0 with value: 0.5301734856591336.
train mae: 0.5176953476700593
train r2: 0.7919612763891766
test mae: 0.5500160748884018
test r2: 0.762542304744819
🏃 View run gifted-wren-161 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/b4ca5db01cd5421b863077699ce7fb38
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5

Best trial: 0. Best value: 0.530173:  10%|█         | 3/30 [01:00<09:25, 20.96s/it]

[I 2025-05-12 09:24:16,730] Trial 3 finished with value: 0.5500160748884018 and parameters: {'n_estimators': 291, 'max_depth': 21, 'max_features': None, 'min_samples_split': 9, 'min_samples_leaf': 7, 'max_samples': 0.6497607447217145, 'bootstrap': True}. Best is trial 0 with value: 0.5301734856591336.
train mae: 0.5119881863649063
train r2: 0.7926283431767931
test mae: 0.5424224719027495
test r2: 0.7683104886418691
train mae: 0.5232061933201926
train r2: 0.7886882022023702
test mae: 0.5714221296749914
test r2: 0.7460135606233135
🏃 View run whimsical-shoat-625 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/2569f636357740778712b240c39bc2e8
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5
🏃 View run victorious-chimp-564 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/9bc7b463f0154a18bead4f53db969146
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5
train mae: 0.5284675602855263
train r2: 0.7846937135078218
test mae: 0.5782582260941153
test r2: 0.7404643465657568
train mae: 0.5889695585586996
train r2: 0.7568708196024851
test mae: 0.5859615601610824
test r2: 0.7532584812841377
train mae: 0.522492987819724
train r2: 0.7874386285680842
test mae: 0.5645178329603734
test r2: 0.7528051629120921
train mae: 0.5087638164646423
train r2: 0.7983703768478208
test mae: 0.5375032280576582
test r2: 0.7740739218312154

Best trial: 0. Best value: 0.530173:  13%|█▎        | 4/30 [01:44<12:51, 29.66s/it]

[I 2025-05-12 09:24:59,734] Trial 8 finished with value: 0.5424224719027495 and parameters: {'n_estimators': 481, 'max_depth': 25, 'max_features': None, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_samples': 0.6316857391408108, 'bootstrap': True}. Best is trial 0 with value: 0.5301734856591336.
train mae: 0.5080873186099064
train r2: 0.800117198082579
test mae: 0.5439970048249538
test r2: 0.769174219839669

Best trial: 0. Best value: 0.530173:  17%|█▋        | 5/30 [01:46<08:12, 19.69s/it]

[I 2025-05-12 09:25:01,749] Trial 10 finished with value: 0.5714221296749914 and parameters: {'n_estimators': 261, 'max_depth': 22, 'max_features': 'sqrt', 'min_samples_split': 6, 'min_samples_leaf': 7, 'max_samples': 0.729300273047431, 'bootstrap': True}. Best is trial 0 with value: 0.5301734856591336.
train mae: 0.5198365470056459
train r2: 0.7912278734918003
test mae: 0.5500004709942328
test r2: 0.7611828359627711
🏃 View run inquisitive-mole-128 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/2cc3aa6377504c70aea800f2aaa7f899
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5
train mae: 0.5093120621996718
train r2: 0.7948500957993373
test mae: 0.5304453915127787
test r2: 0.7803724200550844
🏃 View run blushing-bear-418 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/ccdb08aeaa7a4585a4ce7bdef150b610
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5
🏃 View run charming-chimp-475 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/cb1196f1ce0f4c2b9032818f1fc265ac
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5
🏃 View run aged-swan-226 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/f80407816f414985bef7f5db5af393e8
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5
🏃 View run rumbling-cow-898 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/ada50d6fc5a04c87b1040c2905024b06
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5
🏃 View run auspicious-zebra-753 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/a9bfb7ca2ebc4015810c2751df986c22
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5

Best trial: 0. Best value: 0.530173:  20%|██        | 6/30 [01:58<06:57, 17.41s/it]

[I 2025-05-12 09:25:14,719] Trial 5 finished with value: 0.5782582260941153 and parameters: {'n_estimators': 258, 'max_depth': 14, 'max_features': 'sqrt', 'min_samples_split': 8, 'min_samples_leaf': 9, 'max_samples': 0.7987777234143015, 'bootstrap': True}. Best is trial 0 with value: 0.5301734856591336.
🏃 View run legendary-panda-1000 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/6f80eb2044d64985a70de2eba17b1540
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5

Best trial: 0. Best value: 0.530173:  23%|██▎       | 7/30 [02:01<04:44, 12.37s/it]

[I 2025-05-12 09:25:16,731] Trial 9 finished with value: 0.5859615601610824 and parameters: {'n_estimators': 300, 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_samples': 0.8850251309281996, 'bootstrap': True}. Best is trial 0 with value: 0.5301734856591336.

Best trial: 0. Best value: 0.530173:  27%|██▋       | 8/30 [02:02<03:13,  8.78s/it]

[I 2025-05-12 09:25:17,822] Trial 6 finished with value: 0.5645178329603734 and parameters: {'n_estimators': 20, 'max_depth': 18, 'max_features': 'sqrt', 'min_samples_split': 6, 'min_samples_leaf': 6, 'max_samples': 0.8365529703755297, 'bootstrap': True}. Best is trial 0 with value: 0.5301734856591336.

Best trial: 0. Best value: 0.530173:  30%|███       | 9/30 [02:03<02:12,  6.32s/it]

[I 2025-05-12 09:25:18,744] Trial 11 finished with value: 0.5375032280576582 and parameters: {'n_estimators': 107, 'max_depth': 12, 'max_features': 'log2', 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_samples': 0.8431271029238827, 'bootstrap': True}. Best is trial 0 with value: 0.5301734856591336.

Best trial: 0. Best value: 0.530173:  33%|███▎      | 10/30 [02:05<01:39,  4.99s/it]

[I 2025-05-12 09:25:20,739] Trial 4 finished with value: 0.5439970048249538 and parameters: {'n_estimators': 312, 'max_depth': 18, 'max_features': 'log2', 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_samples': 0.8791388144961143, 'bootstrap': True}. Best is trial 0 with value: 0.5301734856591336.

Best trial: 0. Best value: 0.530173:  37%|███▋      | 11/30 [02:08<01:23,  4.38s/it]

[I 2025-05-12 09:25:23,742] Trial 7 finished with value: 0.5500004709942328 and parameters: {'n_estimators': 259, 'max_depth': 12, 'max_features': None, 'min_samples_split': 7, 'min_samples_leaf': 9, 'max_samples': 0.8500597136390879, 'bootstrap': True}. Best is trial 0 with value: 0.5301734856591336.

Best trial: 0. Best value: 0.530173:  40%|████      | 12/30 [02:10<01:05,  3.66s/it]

[I 2025-05-12 09:25:25,749] Trial 13 finished with value: 0.5304453915127787 and parameters: {'n_estimators': 98, 'max_depth': 28, 'max_features': 'log2', 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_samples': 0.9260386975869233, 'bootstrap': True}. Best is trial 0 with value: 0.5301734856591336.
train mae: 0.5409567602871549
train r2: 0.774968570936232
test mae: 0.5947030186173101
test r2: 0.72676642307417
🏃 View run stately-chimp-220 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/bd57343a5aee4760bff89befa6f6f846
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5

Best trial: 0. Best value: 0.530173:  43%|████▎     | 13/30 [02:34<02:51, 10.11s/it]

[I 2025-05-12 09:25:50,722] Trial 12 finished with value: 0.5947030186173101 and parameters: {'n_estimators': 155, 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_split': 4, 'min_samples_leaf': 10, 'max_samples': 0.5425414750163318, 'bootstrap': True}. Best is trial 0 with value: 0.5301734856591336.
train mae: 0.5081725591345622
train r2: 0.792518633698022
test mae: 0.5333868849188034
test r2: 0.7730608782913494
train mae: 0.5187797672175146
train r2: 0.7914388081253685
test mae: 0.5508370580827193
test r2: 0.7613849537778882
🏃 View run debonair-carp-910 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/a982fe4afdb04f699cf6fcf72e107604
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5
🏃 View run kindly-smelt-350 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/a4800a73a9644214896e09aaa65b1acd
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5
train mae: 0.5214284792370829
train r2: 0.790845528783428
test mae: 0.5359382081573814
test r2: 0.770789411469868

Best trial: 0. Best value: 0.530173:  47%|████▋     | 14/30 [03:10<04:42, 17.65s/it]

[I 2025-05-12 09:26:25,790] Trial 2 finished with value: 0.5333868849188034 and parameters: {'n_estimators': 308, 'max_depth': 19, 'max_features': None, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_samples': 0.5927571332119324, 'bootstrap': True}. Best is trial 0 with value: 0.5301734856591336.

Best trial: 0. Best value: 0.530173:  50%|█████     | 15/30 [03:10<03:09, 12.61s/it]

[I 2025-05-12 09:26:26,720] Trial 14 finished with value: 0.5508370580827193 and parameters: {'n_estimators': 88, 'max_depth': 11, 'max_features': None, 'min_samples_split': 3, 'min_samples_leaf': 6, 'max_samples': 0.6316857624009408, 'bootstrap': True}. Best is trial 0 with value: 0.5301734856591336.
🏃 View run aged-flea-654 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/63a16b3f8f594450985dac900e1b47ff
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5
train mae: 0.5076681712097916
train r2: 0.7933233674421813
test mae: 0.5248203902279704
test r2: 0.7821311843898975

Best trial: 0. Best value: 0.530173:  53%|█████▎    | 16/30 [03:28<03:15, 13.94s/it]

[I 2025-05-12 09:26:43,739] Trial 15 finished with value: 0.5359382081573814 and parameters: {'n_estimators': 96, 'max_depth': 8, 'max_features': None, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_samples': 0.9238483933281766, 'bootstrap': True}. Best is trial 0 with value: 0.5301734856591336.
train mae: 0.5196345480532604
train r2: 0.7797888108606079
test mae: 0.5316801679112925
test r2: 0.7761571228436562
🏃 View run calm-midge-328 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/8bb0114d9db54e8391adf13c8ad55114
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5
train mae: 0.5178445678043333
train r2: 0.7811101244791099
test mae: 0.531080593663858
test r2: 0.7777178479245161
train mae: 0.5390224234479885
train r2: 0.7893079488015498
test mae: 0.5472476157383218
test r2: 0.7810719931515729
🏃 View run nervous-shoat-36 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/ba9df306cb464832aaf808f294f58086
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5
train mae: 0.5182779140197392
train r2: 0.780277054160589
test mae: 0.5332179005882247
test r2: 0.7739488015986676
🏃 View run bittersweet-fish-911 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/4de07e6e331d47c48ef9c7660ad05d25
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5
🏃 View run righteous-bear-530 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/cff52857068b46c8a68f91de5b5153c3
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5
🏃 View run rare-mare-466 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/4bcaaeb5c4e04058bc0a981db8939ea6
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5
train mae: 0.5114664314426024
train r2: 0.7963090685512826
test mae: 0.5552970670596933
test r2: 0.7602624858103685

Best trial: 0. Best value: 0.530173:  57%|█████▋    | 17/30 [03:55<03:52, 17.87s/it]

[I 2025-05-12 09:27:10,763] Trial 22 finished with value: 0.531080593663858 and parameters: {'n_estimators': 125, 'max_depth': 29, 'max_features': 'log2', 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_samples': 0.9754177814121159, 'bootstrap': True}. Best is trial 0 with value: 0.5301734856591336.
train mae: 0.518640408897447
train r2: 0.7802969442115112
test mae: 0.5336751496600584
test r2: 0.7745676108685229

Best trial: 0. Best value: 0.530173:  60%|██████    | 18/30 [03:57<02:37, 13.10s/it]

[I 2025-05-12 09:27:12,741] Trial 17 finished with value: 0.5472476157383218 and parameters: {'n_estimators': 78, 'max_depth': 6, 'max_features': 'log2', 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_samples': 0.5258794213133395, 'bootstrap': True}. Best is trial 0 with value: 0.5301734856591336.

Best trial: 18. Best value: 0.52482:  63%|██████▎   | 19/30 [03:57<01:44,  9.46s/it]

[I 2025-05-12 09:27:13,728] Trial 18 finished with value: 0.5248203902279704 and parameters: {'n_estimators': 150, 'max_depth': 29, 'max_features': 'log2', 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_samples': 0.5052045211887413, 'bootstrap': True}. Best is trial 18 with value: 0.5248203902279704.
train mae: 0.508325003893878
train r2: 0.7937232726722163
test mae: 0.5276261059670782
test r2: 0.7796911980269055

Best trial: 18. Best value: 0.52482:  67%|██████▋   | 20/30 [04:00<01:12,  7.23s/it]

[I 2025-05-12 09:27:15,769] Trial 23 finished with value: 0.5332179005882247 and parameters: {'n_estimators': 147, 'max_depth': 30, 'max_features': 'log2', 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_samples': 0.9870620830772953, 'bootstrap': True}. Best is trial 18 with value: 0.5248203902279704.
🏃 View run selective-tern-466 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/b94bb856b75c47dab38bdcc78a90bd73
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5

Best trial: 18. Best value: 0.52482:  70%|███████   | 21/30 [04:03<00:53,  5.97s/it]

[I 2025-05-12 09:27:18,796] Trial 20 finished with value: 0.5316801679112925 and parameters: {'n_estimators': 128, 'max_depth': 29, 'max_features': 'log2', 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_samples': 0.9889304447052366, 'bootstrap': True}. Best is trial 18 with value: 0.5248203902279704.
🏃 View run rare-fox-161 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/2beb3956d0d642289f57c23836348e0f
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5
🏃 View run abrasive-steed-659 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/f20c3774c0ba4e93aae1eefbc5c84f11
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5

Best trial: 18. Best value: 0.52482:  73%|███████▎  | 22/30 [04:10<00:50,  6.26s/it]

[I 2025-05-12 09:27:25,732] Trial 16 finished with value: 0.5552970670596933 and parameters: {'n_estimators': 137, 'max_depth': 17, 'max_features': 'sqrt', 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_samples': 0.7045428977474975, 'bootstrap': True}. Best is trial 18 with value: 0.5248203902279704.

Best trial: 18. Best value: 0.52482:  77%|███████▋  | 23/30 [04:14<00:39,  5.58s/it]

[I 2025-05-12 09:27:29,740] Trial 24 finished with value: 0.5336751496600584 and parameters: {'n_estimators': 96, 'max_depth': 29, 'max_features': 'log2', 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_samples': 0.9553791229079706, 'bootstrap': True}. Best is trial 18 with value: 0.5248203902279704.
train mae: 0.5203922138100978
train r2: 0.7782141126724172
test mae: 0.5346092825757315
test r2: 0.772067678636408

Best trial: 18. Best value: 0.52482:  80%|████████  | 24/30 [04:18<00:30,  5.11s/it]

[I 2025-05-12 09:27:33,752] Trial 19 finished with value: 0.5276261059670782 and parameters: {'n_estimators': 120, 'max_depth': 28, 'max_features': 'log2', 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_samples': 0.5151955740555254, 'bootstrap': True}. Best is trial 18 with value: 0.5248203902279704.
🏃 View run intrigued-shark-826 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/6d9db0ec891941ccb055d566124cec3b
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5
train mae: 0.5135008472906634
train r2: 0.7892899136270315
test mae: 0.5408906270851807
test r2: 0.7691245173544896
train mae: 0.5042487777460811
train r2: 0.7995201251681407
test mae: 0.5326430899707951
test r2: 0.7783061352784773

Best trial: 18. Best value: 0.52482:  83%|████████▎ | 25/30 [04:27<00:31,  6.27s/it]

[I 2025-05-12 09:27:42,737] Trial 21 finished with value: 0.5346092825757315 and parameters: {'n_estimators': 136, 'max_depth': 30, 'max_features': 'log2', 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_samples': 0.9951025312233204, 'bootstrap': True}. Best is trial 18 with value: 0.5248203902279704.
🏃 View run spiffy-cow-217 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/bc2425dce28b444583f6908339bf19a3
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5
🏃 View run chill-boar-422 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/e2a871fa2ece4cc78b851577ee199966
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5

Best trial: 18. Best value: 0.52482:  87%|████████▋ | 26/30 [04:35<00:28,  7.09s/it]

[I 2025-05-12 09:27:51,729] Trial 26 finished with value: 0.5408906270851807 and parameters: {'n_estimators': 19, 'max_depth': 30, 'max_features': 'log2', 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_samples': 0.9989862524369482, 'bootstrap': True}. Best is trial 18 with value: 0.5248203902279704.

Best trial: 18. Best value: 0.52482:  90%|█████████ | 27/30 [04:37<00:15,  5.26s/it]

[I 2025-05-12 09:27:52,736] Trial 25 finished with value: 0.5326430899707951 and parameters: {'n_estimators': 175, 'max_depth': 30, 'max_features': 'log2', 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_samples': 0.998521594329024, 'bootstrap': True}. Best is trial 18 with value: 0.5248203902279704.
train mae: 0.5174260934259498
train r2: 0.7812803625656339
test mae: 0.5356212436153516
test r2: 0.7717234659680561
🏃 View run bright-wolf-208 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/86faa11f52944618ac92334145111e15
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5
train mae: 0.5066823431078922
train r2: 0.8001999233041179
test mae: 0.5386752288888492
test r2: 0.7751679199642362

Best trial: 18. Best value: 0.52482:  93%|█████████▎| 28/30 [04:45<00:12,  6.09s/it]

[I 2025-05-12 09:28:00,761] Trial 27 finished with value: 0.5356212436153516 and parameters: {'n_estimators': 189, 'max_depth': 30, 'max_features': 'log2', 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_samples': 0.968321368902664, 'bootstrap': True}. Best is trial 18 with value: 0.5248203902279704.
train mae: 0.5058867143313213
train r2: 0.7972613775304117
test mae: 0.5318413797569803
test r2: 0.7782144389144564
🏃 View run omniscient-pug-547 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/a389a27203b4443fb6fa2d5a9cf8f2fd
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5
🏃 View run secretive-mule-368 at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/89b74a6c4ddf43e88a933356cfbff25a
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5

Best trial: 18. Best value: 0.52482:  97%|█████████▋| 29/30 [04:49<00:05,  5.46s/it]

[I 2025-05-12 09:28:04,738] Trial 28 finished with value: 0.5386752288888492 and parameters: {'n_estimators': 187, 'max_depth': 25, 'max_features': 'log2', 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_samples': 0.7185920447784611, 'bootstrap': True}. Best is trial 18 with value: 0.5248203902279704.

Best trial: 18. Best value: 0.52482: 100%|██████████| 30/30 [04:50<00:00,  9.67s/it]

[I 2025-05-12 09:28:05,736] Trial 29 finished with value: 0.5318413797569803 and parameters: {'n_estimators': 174, 'max_depth': 24, 'max_features': 'log2', 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_samples': 0.7267083449920694, 'bootstrap': True}. Best is trial 18 with value: 0.5248203902279704.

2025/05/12 09:28:30 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/05/12 09:28:59 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run best_model at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5/runs/409dd7775c9045fda7daa0b558514b55
🧪 View experiment at: https://dagshub.com/AMR-ITH/RealEstateInsights.mlflow/#/experiments/5

In [22]:
study.best_params

{'n_estimators': 150,
 'max_depth': 29,
 'max_features': 'log2',
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_samples': 0.5052045211887413,
 'bootstrap': True}

In [23]:
# train the model on best parameters
best_rf = RandomForestRegressor(**study.best_params)

best_rf.fit(X_train_trans,y_train)

y_pred_train = best_rf.predict(X_train_trans)
y_pred_test = best_rf.predict(X_test_trans)



scores = cross_val_score(best_rf,X_train_trans,y_train,cv=5,n_jobs=-1)

# mae,r2 for test and train
mae_train = mean_absolute_error(y_train,y_pred_train)
r2_train = r2_score(y_train,y_pred_train)
mae_test = mean_absolute_error(y_test,y_pred_test)
r2_test = r2_score(y_test,y_pred_test)


print(mae_train)
print(r2_train)
print(mae_test)
print(r2_test)

0.3076572094211611
0.9242606163424838
0.4657499930855609
0.8333173218097839